// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inyefdcwiwcursurmlik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlueWVmZGN3aXdjdXJzdXJtbGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzk1NTIsImV4cCI6MjA3Mzc1NTU1Mn0.iViJePr-B8gx2aISZPts9XecX1bgXv1xcOS4iG2QBQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
